app.modules.global.currentLang = config.languages.en.code;

i18n.Dictionary = {

    global: {
        'Dashboard': 'Dashboard',
        'Authentication': 'Authentication',
        'Membership': 'Membership',
        'Logout': 'Logout',
        'Your investments': 'Your investments',

        'Choose the payment': 'Choose the payment',
        'Account Settings': 'Account Settings',
        'Fill the form in order to change your password.': 'Fill the form in order to change your password.',
        'Old Password': 'Old Password',
        'Enter old password': 'Enter old password',
        'Enter new password': 'Enter new password',
        'New Password': 'New Password',
        'New Password Confirmation': 'New Password Confirmation',
        'Repeat new password': 'Repeat new password',
        'Changed': 'Changed',
        'Change': 'Change',
        'copied': 'copied',
        'copy': 'copy',
        'Investments': 'Investments',
        'First round': 'First round',
        'Second round': 'Second round',
        'Third round': 'Third round',
        'Fourth round': 'Fourth round',
        'Get': 'Get',
        'bonus': 'bonus',
        'June': 'June',
        'July': 'July',
        'Total Investors': 'Total Investors',
        'We connect investors and help grow the economy. Weâ€™ve taken this progress global.': 'We connect investors and help grow the economy. Weâ€™ve taken this progress global.',
        'We have raised millions of equity capital from some of the largest and most sophisticated investors in the world.': 'We have raised millions of equity capital from some of the largest and most sophisticated investors in the world.',
        'Join a global community of more than 145,000 investment professionals dedicated to efficient markets and high ethical standards.': 'Join a global community of more than 145,000 investment professionals dedicated to efficient markets and high ethical standards.',
        'Our effective referral system maintains a close relationship between all levels of investors and helps to ensure people receive the best possible return on investment.': 'Our effective referral system maintains a close relationship between all levels of investors and helps to ensure people receive the best possible return on investment.',
        'Share this link to invite friends and partners': 'Share this link to invite friends and partners',
        'Accounts': 'Accounts',
        'Email': 'Email',
        'Bought ATB Coins': 'Bought ATB Coins',
        'ATB Coin Bonus': 'ATB Coin Bonus',
        'Disable 2FA': 'Disable 2FA',
        'Warning': 'Warning',
        'Disabling 2FA will make your account less secure.': 'Disabling 2FA will make your account less secure.',
        'Password': 'Password',
        'Enter password': 'Enter password',
        'Code': 'Code',
        'For extra account security, you can turn on two-factor authentication (2FA). ATB Coin uses Google Authenticator for 2FA. In order to use 2FA, scan the QR code to the right into the Google Authenticator app on your phone, or enter the 32-digit key that appears under the QR code. Input the six-digit code provided by the Google Authenticator app and your account password below, then click "Enable 2FA".': 'For extra account security, you can turn on two-factor authentication (2FA). ATB Coin uses Google Authenticator for 2FA. In order to use 2FA, scan the QR code to the right into the Google Authenticator app on your phone, or enter the 32-digit key that appears under the QR code. Input the six-digit code provided by the Google Authenticator app and your account password below, then click "Enable 2FA".',
        'QR-Code': 'QR-Code',
        'Enable 2FA': 'Enable 2FA',
        '32-Digit Key': '32-Digit Key',
        'Important': 'Important',
        'Before turning on 2FA, write down or print a copy of your 32-digit key and put it in a safe place. If your phone gets lost, stolen, or erased, you will need this key to get back into your account!': 'Before turning on 2FA, write down or print a copy of your 32-digit key and put it in a safe place. If your phone gets lost, stolen, or erased, you will need this key to get back into your account!',
        'Print a backup of your recovery key.': 'Print a backup of your recovery key.',
        'I have backed up my 32-digit key': 'I have backed up my 32-digit key',

        'Verify Your Account': 'Verify Your Account',
        'Thank you for signing up.': 'Thank you for signing up.',
        'Confirm your email address to activate your account.': 'Confirm your email address to activate your account.',

        'Two Factor Authentication Disabled': 'Two Factor Authentication Disabled',

        'NOTE': 'NOTE',
        'This code changes each time you enable 2FA. If you disable 2FA this code will no longer be valid.': 'This code changes each time you enable 2FA. If you disable 2FA this code will no longer be valid.',

    }

}